import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { EmployeeService } from 'src/app/services/employee.service';
import { Employee } from 'src/app/model/employee.model';

@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.css']
})
export class EmployeeComponent {
  employeeForm: FormGroup;
  isLoading = false;

  constructor(private fb: FormBuilder, private employeeService: EmployeeService) {
    this.employeeForm = this.fb.group({
      empName: ['', [Validators.required, Validators.maxLength(50)]],
      email: ['', [Validators.required, Validators.email]]
    });
  }

  onSubmit(): void {
    if (this.employeeForm.valid) {
      this.isLoading = true;

      const newEmployee: Employee = {
        empId: 0, // Assuming ID is generated by server
        empName: this.employeeForm.value.empName,
        email: this.employeeForm.value.email
      };

      this.employeeService.saveEmployee(newEmployee).subscribe({
        next: () => {
          alert('Employee saved successfully');
          this.isLoading = false;
          this.employeeForm.reset();
        },
        error: () => {
          alert('Failed to save employee');
          this.isLoading = false;
        }
      });
    }
  }

  onReset(): void {
    this.employeeForm.reset();
  }
}
